// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-doctors.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_doctors_default = defineTool({
  name: "list_doctors",
  title: "Listar profissionais da cl\xEDnica",
  description: "Retorna os profissionais/doutores cadastrados na cl\xEDnica, com nome e status ativo.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("clinic_doctors").select("id, name, is_active").order("name");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { doctors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-clients.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_clients_default = defineTool2({
  name: "list_clients",
  title: "Listar clientes/pacientes",
  description: "Retorna os clientes/pacientes cadastrados, filtrando opcionalmente por nome. Limite m\xE1ximo 100.",
  inputSchema: {
    search: z.string().nullable().describe("Filtro opcional por nome do cliente"),
    limit: z.number().int().min(1).max(100).nullable().describe("M\xE1ximo de resultados (padr\xE3o 50)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser2(ctx);
    const take = limit ?? 50;
    let query = supabase.from("clients").select("id, name, phone, assigned_to").limit(take);
    if (search && search.trim().length > 0) {
      query = query.ilike("name", `%${search.trim()}%`);
    }
    const { data, error } = await query.order("name");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} clientes encontrados` }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-routine-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_routine_tasks_default = defineTool3({
  name: "list_routine_tasks",
  title: "Listar tarefas de rotina",
  description: "Retorna todas as tarefas de rotina configuradas, com t\xEDtulo, setor e ordem.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("routine_tasks").select("id, title, sector_id, sort_order, is_active").order("sort_order");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} tarefas de rotina` }],
      structuredContent: { tasks: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/agenda-by-date.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var agenda_by_date_default = defineTool4({
  name: "get_agenda_by_date",
  title: "Consultar agenda cl\xEDnica de um dia",
  description: "Retorna a agenda cl\xEDnica (consultas) para uma data espec\xEDfica no formato YYYY-MM-DD (timezone America/Sao_Paulo).",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Data no formato YYYY-MM-DD")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser4(ctx);
    const { data, error } = await supabase.from("clinic_appointments").select("id, patient_name, doctor_external_id, start_time, end_time, status, appointment_type").gte("start_time", `${date}T00:00:00-03:00`).lte("start_time", `${date}T23:59:59-03:00`).order("start_time");
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Encontrados ${data?.length ?? 0} agendamentos para ${date}` }],
      structuredContent: { date, appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ttgyohcmhapqlnrllfxo";
var mcp_default = defineMcp({
  name: "rotina-pro-alivi-mcp",
  title: "Rotina Pro Alivi \u2014 MCP",
  version: "0.1.0",
  instructions: "Ferramentas de leitura sobre a opera\xE7\xE3o da cl\xEDnica Alivi: agenda cl\xEDnica, profissionais, clientes/pacientes e tarefas de rotina. Todas as chamadas rodam com a identidade do usu\xE1rio autenticado (RLS aplicada).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_doctors_default, list_clients_default, list_routine_tasks_default, agenda_by_date_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
